name = "read-entry-redirect"
main = "index.js"
compatibility_date = "2024-05-10"

account_id = "d6a1f43dd0b2d4efd5e301baa532fe30"
workers_dev = false

routes = [
  # For www subdomain
  { pattern = "www.mayous.org/read", zone_id = "e08ad294b9b7b4afdde5a0bf16a0e862" },
  { pattern = "www.mayous.org/read/*", zone_id = "e08ad294b9b7b4afdde5a0bf16a0e862" },

  # For root domain (no www)
  { pattern = "mayous.org/read", zone_id = "e08ad294b9b7b4afdde5a0bf16a0e862" },
  { pattern = "mayous.org/read/*", zone_id = "e08ad294b9b7b4afdde5a0bf16a0e862" }
]
