name = "read-entry-redirect"
account_id = "d6a1f43dd0b2d4efd5e301baa532fe30"
compatibility_date = "2024-05-10"
main = "index.js"
workers_dev = false  # ✅ Required to disable *.workers.dev and use route

routes = [
  { pattern = "www.mayous.org/read", custom_domain = true }
]
